#
# Required environment variables in the travis config
#
# DOCKER_USERNAME
#
language: cpp
cache: ccache

git:
  submodules: false

stages:
  - name: Test

env:
  global:
    - QT_INSTALL_DIR=~/Qt
    - QT_VERSION=5.12.6
    - QTCREATOR_VERSION=4.10.2
    - QMAKE_PATH=${QT_INSTALL_DIR}/${QT_VERSION}/clang_64/bin/qmake
    - PATH="${QT_INSTALL_DIR}/Qt Creator.app/Contents/MacOS:${PATH}"
    - QBS_BUILD_PROFILE=qt

jobs:
  include:
    - &build-on-macos
      stage: Build Qbs and and run autotests
      name: With Qbs on macOS (xcode 11.3)
      os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - ccache
            - p7zip
          update: true
      before_install:
        - ./scripts/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} qtbase qttools qtscript
        - ./scripts/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QTCREATOR_VERSION} qtcreator
      script:
        - ccache -s
        - qbs setup-toolchains --detect
        - qbs setup-qt ${QMAKE_PATH} qt
        - qbs config profiles.qt.baseProfile xcode-macosx-x86_64
        - qbs config defaultProfile qt
        - qbs config --list profiles
        - scripts/test.sh
      after_failure:
        - find ~/Library/Logs/DiagnosticReports/ \( -name "qbs*.crash" -o -name "tst*.crash" \) | xargs -I {} cat {}

    - <<: *build-on-macos
      env:
        - VAL2=2

    - <<: *build-on-macos
      env:
        - VAL3=3

    - <<: *build-on-macos
      env:
        - VAL4=4

    - <<: *build-on-macos
      env:
        - VAL5=5
