version: "3.3"

services:
  stretch:
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:stretch
    build:
      dockerfile: docker/stretch/Dockerfile
      context: .
      args:
        QT_VERSION: 5.12.4
        QTCREATOR_VERSION: 4.9.2
    working_dir: /qbs
    volumes:
      - .:/qbs
    network_mode: bridge
    cap_add:
        - SYS_PTRACE
