version: "3.7"

x-default-service: &linux
  working_dir: /qbs
  environment:
    - BUILD_OPTIONS
  volumes:
    - .:/qbs
    - ~/.ccache:/home/devel/.ccache
  network_mode: bridge
  cap_add:
      - SYS_PTRACE

services:
  bionic:
    << : *linux
    hostname: bionic
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-5.12.6_1.14.1-4
    build:
      dockerfile: docker/bionic/Dockerfile
      context: .
      args:
        QT_VERSION: 5.12.6
        QTCREATOR_VERSION: 4.10.2

  bionic-android-513:
    << : *linux
    hostname: bionic-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-android-5.13.2-1
    build:
      dockerfile: docker/bionic/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.13.2

  bionic-android-514:
    << : *linux
    hostname: bionic-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-android-5.14.0-1
    build:
      dockerfile: docker/bionic/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.14.0

  stretch:
    << : *linux
    hostname: stretch
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:stretch
    build:
      dockerfile: docker/stretch/Dockerfile
      context: .
      args:
        QT_VERSION: 5.12.4
        QTCREATOR_VERSION: 4.9.2
